### ISSUE TITLE
google-cloud-python release PR creation failed.

### ISSUE THREAD

**Issue by tseaver** [googleapis/releasetool#179]
After successfully creating the `release-storage-1.5.0` branch, failed with:

```bash
> Creating release pull request.
Traceback (most recent call last):
  File "../../gcp-tools/bin/releasetool", line 10, in <module>
    sys.exit(main())
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/__main__.py", line 102, in start
    return releasetool.commands.start.python.start()
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/commands/start/python.py", line 212, in start
    create_release_pr(ctx)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/commands/start/python.py", line 184, in create_release_pr
    body="This pull request was generated using releasetool.",
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/github.py", line 68, in create_pull_request
    response.raise_for_status()
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/googleapis/google-cloud-python/pulls
```

**Comment by busunkim96** [comment]
@tseaver Could you try re-adding the token?

> If you need to change the GitHub API token associated with releasetool, run `releasetool reset-config`. This will delete the existing token. The next time you run `releasetool start` you will be prompted to enter a new token.

**Comment by tseaver** [comment]
OK, I've done that.  I wonder if it would be sensible to run an API request early in the process to check that the token is present / valid, and emit a more useful message if not.
