### ISSUE TITLE
Reporting successful release back to PR failed with `raise Exception("Could exchange certificate for JWT.")`

### ISSUE THREAD

**Issue by busunkim96** [googleapis/releasetool#339]
This was observed in https://github.com/googleapis/python-dialogflow-cx/pull/102.

The release succeeded but the reporter did not report back to the PR at the end of the build.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/releasetool/__main__.py", line 213, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/releasetool/__main__.py", line 193, in publish_reporter_finish
    releasetool.commands.publish_reporter.finish(github_token, pr, status, details)
  File "/usr/local/lib/python3.9/site-packages/releasetool/commands/publish_reporter.py", line 131, in finish
    github_token = releasetool.github.GitHubToken.token_from_dict(
  File "/usr/local/lib/python3.9/site-packages/releasetool/github.py", line 83, in token_from_dict
    access_token = get_installation_access_token(
  File "/usr/local/lib/python3.9/site-packages/releasetool/github.py", line 122, in get_installation_access_token
    raise Exception("Could exchange certificate for JWT.")
Exception: Could exchange certificate for JWT.
Release status reported.
```

[full log](https://fusion2.corp.google.com/invocations/72b8c7aa-bfd9-4c56-a792-5e150c957307/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-dialogflow-cx%2Frelease%2Frelease/log)

Another release on the same day in the same repo didn't have this problem (https://github.com/googleapis/python-dialogflow-cx/pull/106).

**Comment by busunkim96** [comment]
This was resolved in later releases and is no longer a problem.
