### ISSUE TITLE
Tag job is always failing.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/releasetool#353]
I checked the history on fusion, and it's always failing.

```
Processing chore: release 0.17.1-SNAPSHOT: https://github.com/googleapis/java-pubsublite/pull/759
command github-release failed
---------
MissingReleaseNotesError: could not find changelog entry corresponding to release 0.17.1-SNAPSHOT
    at Object.extractReleaseNotes (/tmpfs/src/github/releasetool/node_modules/release-please/build/src/util/release-notes.js:29:15)
    at JavaYoshi.buildReleaseForVersion (/tmpfs/src/github/releasetool/node_modules/release-please/build/src/release-pr.js:347:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async GitHubRelease.createRelease (/tmpfs/src/github/releasetool/node_modules/release-please/build/src/github-release.js:35:25)
    at async GitHubRelease.run (/tmpfs/src/github/releasetool/node_modules/release-please/build/src/github-release.js:47:38)
CalledProcessError(1, ['npx', 'release-please', 'github-release', '--token=/tmp/tmpupjupxhu', '--default-branch=master', '--release-type=java-yoshi', '--bump-minor-pre-major=true', '--repo-url=googleapis/java-pubsublite', '--package-name=', '--debug'])
Processing chore: release 0.2.2: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/139
Closed, not merged, skipping.
HTTPError('403 Client Error: Forbidden for url: https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-python-connector/issues/139/labels')
cleanup


[ID: 8616465] Build finished after 77 secs, exit value: 2
```

**Comment by bcoe** [comment]
Bumping up to a `p1`, as I believe this could be breaking Java releases.

**Comment by chingor13** [comment]
This was a weird edgecase where a release PR was opened for a release, but then re-used for a snapshot release. snapshot releases cannot actually be released and do not normally have the `autorelease: pending` label.
