### ISSUE TITLE
Unprocessable entity for url:

### ISSUE THREAD

**Issue by tseaver** [googleapis/releasetool#65]
```python
$ ../../gcp-tools/bin/releasetool tag
o/ Hey, tseaver, let's tag a release!
> Determining GitHub context.
Origin: tseaver/google-cloud-python, Upstream: GoogleCloudPlatform/google-cloud-python
> Let's figure out which pull request corresponds to your release.
> Please pick one of the following PRs:

	1: Release api_core 1.4.1 (6133)
	2: Release dlp 0.8.0 (6106)
	3: Release dlp 0.8.0 (6105)

Which one do you want to tag and release?: 1
> Determining what the release tag should be.
Release tag is api_core-1.4.1.
> Determining the package name and version.
Package name: api_core, package version: 1.4.1.
> Grabbing the release notes.
> Creating the release.
Traceback (most recent call last):
  File "../../gcp-tools/bin/releasetool", line 11, in <module>
    sys.exit(main())
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/main.py", line 112, in tag
    return releasetool.commands.tag.python.tag()
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/commands/tag/python.py", line 151, in tag
    create_release(ctx)
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/commands/tag/python.py", line 112, in create_release
    body=ctx.release_notes,
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/releasetool/github.py", line 89, in create_release
    response.raise_for_status()
  File "/home/tseaver/projects/agendaless/Google/src/gcp-tools/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repositories/16316451/releases
```

**Comment by theacodes** [comment]
I *think* this is because we just moved to `googleapis`. If you update your remotes does it fix it?

**Comment by tseaver** [comment]
I have been able to tag releases since updating remotes.
