### ISSUE TITLE
syntax error running `releasetool start` after fresh pip install

### ISSUE THREAD

**Issue by soldair** [googleapis/releasetool#68]
```
Traceback (most recent call last):
  File "/usr/local/bin/releasetool", line 7, in <module>
    from releasetool.main import main
  File "/usr/local/lib/python3.5/dist-packages/releasetool/main.py", line 82
    prompt=f"Which language ({', '.join(_language_choices)})?",
                                                             ^
SyntaxError: invalid syntax
```

**Comment by JustinBeckwith** [comment]
This makes me wonder if releasetool is getting run with Python 2 instead of 3 :)

**Comment by soldair** [comment]
i was wondering this too but my release tool has the correct shebang
/usr/local/bin/releasetool
```
#!/usr/bin/python3

# -*- coding: utf-8 -*-
.......
```

**Comment by busunkim96** [comment]
It looks like Python 3.5 is being used, but you'll need 3.6 or 3.7 because of the formatted string literal  https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals. Could you try again with 3.6/3.7?

**Comment by soldair** [comment]
thanks. I can upgrade. python 3.5 is what comes on workstations so some updated docs for this would be great.

**Comment by JustinBeckwith** [comment]
@busunkim96 could we throw with an error message if the user tries to use this with an older version?
