### ISSUE TITLE
Releasetool using YYYY.mm.dd versioning for package that expects semver

### ISSUE THREAD

**Issue by crwilcox** [googleapis/releasetool#93]
```
(venv) crwilcox@redrover ~/w/r/g/datastore> releasetool start --language python                                                                                                                                                     master?
o/ Hey, crwilcox, let's release some stuff!
> Determining GitHub context.
Origin: googleapis/google-cloud-python, Upstream: googleapis/google-cloud-python
> Comparing origin/master to master.
master is up to date with origin/master
> Figuring out the package name.
Looks like we're releasing datastore.
> Figuring out what the last release was.
From github.com:googleapis/google-cloud-python
 * [new branch]            release-datastore-2018.10.29 -> origin/release-datastore-2018.10.29
The last release was 1.7.0.
> Gathering changes since 1.7.0
Cool, 9 changes found.
> Opening your editor to finalize release notes.
Releasing 2018.10.29.
> Creating branch release-datastore-2018.10.29
fatal: A branch named 'release-datastore-2018.10.29' already exists.
Traceback (most recent call last):
  File "/Users/crwilcox/workspace/releasetool/venv/bin/releasetool", line 11, in <module>
    sys.exit(main())
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/releasetool/main.py", line 101, in start
    return releasetool.commands.start.python.start()
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/releasetool/commands/start/python.py", line 198, in start
    create_release_branch(ctx)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/releasetool/commands/start/python.py", line 130, in create_release_branch
    return releasetool.git.checkout_create_branch(ctx.release_branch)
  File "/Users/crwilcox/workspace/releasetool/venv/lib/python3.7/site-packages/releasetool/git.py", line 46, in checkout_create_branch
    subprocess.check_output(["git", "checkout", "-b", branch_name, base])
  File "/Users/crwilcox/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/Users/crwilcox/.pyenv/versions/3.7.0/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'checkout', '-b', 'release-datastore-2018.10.29', 'master']' returned non-zero exit status 128.
```

**Comment by crwilcox** [comment]
For now I have reverted to using 0.10.0. I had installed 2018.10.25
